const moduloA = require('./aula01_moduloa')
const moduloB = require('./aula01_modulob')

console.log(moduloA.ola)
console.log(moduloA.bemVindo)
console.log(moduloA.ateLogo)
console.log(moduloA)
console.log(moduloB.bomDia)
console.log(moduloB.boaNoite())
console.log(moduloB)